# Idea is to map a hashing value generated by a hashing algorithm to keys of original dictionary
import cmath

def generate_hashing_code(key):
    
    complex_hash = 0
    for i in range(len(key)):
        complex_hash += (ord(key[i]) * i)
    
    final_hash = complex_hash * cmath.log(abs(cmath.e + cmath.pi * 1j))

    return int(abs(final_hash))


# CREATE OUR NEW DICTIONRAY WHERE HASH VALUES ARE MAPPED TO ORIGINAL KEYS
def create_new_dict(original_dict):
    new_dict = {}   # EMPTY DICTIONARY

    for key in original_dict.keys():
        hash = generate_hashing_code(key)   # GENERATE HASH VALUE FOR EACH KEY OF ORIGINAL DICTIONARY
        new_dict[hash] = key    # MAP THE HASHING VALUE TO THE ORIGINAL KEYS

    return new_dict

def get_value(key, original, new):
    hash_value = generate_hashing_code(key) # GET THE HASH VALUE OF THE KEY

    return original[new[hash_value]]
    
    

# STEP 1 --> INPUT ORIGINAL DICTIONARY
n = int(input('Enter how many items you need in a dictionary: '))
original_dictionary = {input('KEY: '): input('VALUE: ') for i in range(n)}

key_mapped_to = input('Enter the key you have: ')

new = create_new_dict(original_dictionary)

if key_mapped_to in original_dictionary.keys():
    result = get_value(key_mapped_to, original_dictionary, new)
    print(f"{key_mapped_to} -> {result}")
else:
    print('ERROR! Your key is not found in our dictionary.')




